### PR TITLE
dark mode enabled

### LINKED ISSUE #33: Adding Dark mode
I want to add the dark mode in your website
@lazyjinchuriki please assign this issue to me under hactoberfest2023

### PR DESCRIPTION
**Pull request by aditya9855**
https://github.com/lazyjinchuriki/pokedex/assets/62770104/24e1d525-493f-46ea-a432-39e4860b570d

- dark mode created
- Closes #33

### CODE REVIEW

**Comment by aditya9855** [comment]
@lazyjinchuriki please review this pull request and requested to merge under hacktoberfest 2023

**Comment by lazyjinchuriki** [comment]
Is this mobile responsive?

**Comment by aditya9855** [comment]
> Is this mobile responsive?

@lazyjinchuriki yes it is resposive

**Comment by lazyjinchuriki** [comment]
Show me please.

**Comment by aditya9855** [comment]
> Show me please.

https://github.com/lazyjinchuriki/pokedex/assets/62770104/8d8ad663-8c1c-4a3d-8fa3-f30a4f8678b5

**Comment by lazyjinchuriki** [comment]
Do one thing make a separate segment below the navbar for the dark mode toggle and make the Github logo as it was back then.
Maybe in future, can add more features in that segment.

**Comment by lazyjinchuriki** [comment]
Do one thing make a separate segment below the navbar for the dark mode toggle and make the Github logo as it was back then.
Maybe in future, can add more features in that segment.

**Comment by aditya9855** [comment]
> Do one thing make a separate segment below the navbar for the dark mode toggle and make the Github logo as it was back then. Maybe in future, can add more features in that segment.

sure i'll make

**Comment by aditya9855** [comment]
@lazyjinchuriki please review this and merge it underhactoberfest2023


https://github.com/lazyjinchuriki/pokedex/assets/62770104/0cb25841-15c0-491c-aeb2-bf2b6fcf4623

**Pull request merged**
